SSID = "FeiLong_Route"
PASSWORD = "QweR0219"
HOSTNAME = "Wifi-Gyro"
PORT = 26760
WAITTIME = 3000
IICID = 0
IICSDA = 2
IICSCL = 1
MPUADDR = 0x68
COMPILELUA = true
COMPILECHECKFILE = '.compile'
debugLevelMessage = {'debug', 'info', 'warning', 'error'}
DEBUGLEVEL = 2
MaxPointLength = 60
